// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: env(['production', 'preview'].includes(env('VERCEL_ENV')) ? 'DATABASE_URL' : 'DATABASE_URL_UNPOOLED'),
  },
});
//TODO: restaturar rama main una vez se haya deployado la primera versión